### ISSUE TITLE
Couldn't manage to clone then run locally or on Glitch either on Chrome or Firefox

### ISSUE THREAD

**Issue by Utopiah** [ModelDepot/tfjs-yolo-tiny#10]
Cloning the repository and building locally with node v10.1.0 fails me with : 

Firefox
![image](https://user-images.githubusercontent.com/1076655/40269904-c7cd6ef0-5b84-11e8-9969-52428f447525.png)

Chrome
![image](https://user-images.githubusercontent.com/1076655/40269911-f48fc4ec-5b84-11e8-9776-f8e98811e0ce.png)

Also tried on Glitch but couldn't even run it getting a "/etc/app-types/node/start.sh: line 43: null: command not found". I briefly tried in the console to do a `npm run serve` but it didn't end.

The tf.js version used was ... whatever the default configuration offered Saturday so I assume 0.11. I will try pinned down to 0.9 if it makes a difference. I didn't dig in detail but I'm wondering if it's not related to how the content is passed via `src/webcam.js`.

PS: was initially added to https://github.com/ModelDepot/tfjs-yolo-tiny-demo/issues/

**Comment by MikeShi42** [comment]
@Utopiah Ah I originally assumed it'd be a tf.js related issue since the exception was being thrown from in the lib it seems (and I have not had a chance to test with 0.11). But I can see how the webcam capture can be an issue. Thanks for moving the issue over and providing the stack traces! I'll try to dig into this as well. Let me know if 0.9 works out though :)

**Comment by thies1006** [comment]
thank you for this nice project. however i also ran into the same problem and it seems that this bug appears when using 0.11 (locally). i am using now 0.10 and it seem to work.

**Comment by MikeShi42** [comment]
Just updated the lib (v1.0.1) to work with tfjs@0.13. Closing for now, feel free to re-open if this problem persists with the newest version.
