### ISSUE TITLE
Can you provide more information code about the web page?

### ISSUE THREAD

**Issue by a6225301** [ModelDepot/tfjs-yolo-tiny#20]
Hi, i have trained a model as your previous introduction and the model seems work well. However, i want to deploy it on the browser and use the camera to detect object just same as your example. And i am not quite familar with how to code it on the front-page html, can you provide more information code about the web page (html) to use that model ? Thanks a lot.

**Comment by MikeShi42** [comment]
You can find the repo that powers the live demo here: https://github.com/ModelDepot/tfjs-yolo-tiny-demo :)
