### ISSUE TITLE
help ? 

### ISSUE THREAD

**Issue by hiddentn** [ModelDepot/tfjs-yolo-tiny#5]
can you explain to me where are the weights please ?  ,thanks 

&& btw look at these numbers  :)
![screenshot 1](https://user-images.githubusercontent.com/31354864/38759855-d0edd398-3f6f-11e8-857f-71ab8b597332.png)
GTX850M

**Comment by MikeShi42** [comment]
That's awesome! 5fps! :D

For a zip of the weight files used, you can check it out on ModelDepot, clicking on "Download Model" https://modeldepot.io/mikeshi/tiny-yolo-in-javascript

The location reference in this package is [here](https://github.com/ModelDepot/tfjs-yolo-tiny/blob/master/src/index.js#L17-L18) in the source code. You can check out the repo hosting the weight files [here](https://github.com/MikeShi42/yolo-tiny-tfjs) (it's a bit of a mess, the config file is `model2.json`)

Ideally I can get it hosted somewhere better than GH but we don't have the data transfer capacity at ModelDepot to justify hosting the live model version there for now (hopefully in the future we can though!).

The weights were created through pulling the weights from the original [darknet website](https://pjreddie.com/darknet/yolo/), passing it through YAD2k ([see this issue](https://github.com/allanzelener/YAD2K/issues/83#issuecomment-364649222) for loading tiny yolo weights), and then using tfjs's keras -> tfjs convertor to create the ultimate tf.js model weights.

Let me know if you have any further questions :)
