### ISSUE TITLE
Indices must be of dtype int32

### ISSUE THREAD

**Issue by vanderlin** [ModelDepot/tfjs-yolo-tiny#9]
![image](https://user-images.githubusercontent.com/149997/39948347-93cd8b90-5543-11e8-9a02-0fd4ddf51c4a.png)

Just tried to build right from the demo, but get this error?

**Comment by MikeShi42** [comment]
@vanderlin can you confirm this is fixed in the latest commit? If not, please re-open :)

**Comment by samilkorkmaz** [comment]
I built the demo on a Win10 PC and got a similar error.

![image](https://user-images.githubusercontent.com/9883871/41933885-c6271340-798d-11e8-8b0d-d6fa1e71bc9f.png)
